# Generated by Django 4.1.6 on 2023-03-25 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DropIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(verbose_name='drop in datetime')),
                ('visible', models.BooleanField(default=False, help_text='Makes this drop in visible on the website for users')),
            ],
        ),
        migrations.CreateModel(
            name='Rink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropins.dropin')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='sign up datetime')),
                ('paid', models.BooleanField(default=False)),
                ('rostered', models.BooleanField(default=False)),
                ('isGoalie', models.BooleanField(default=False)),
                ('isWhiteTeam', models.BooleanField(default=False, help_text='Denotes if player is on the white team')),
                ('dropInId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropins.dropin')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_team_name', models.CharField(max_length=50)),
                ('losing_team_name', models.CharField(max_length=50)),
                ('winning_score', models.IntegerField(default=0)),
                ('losing_score', models.IntegerField(default=0)),
                ('dropInId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropins.dropin')),
            ],
        ),
        migrations.AddField(
            model_name='dropin',
            name='rink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dropins.rink'),
        ),
    ]
