# Generated by Django 4.1.6 on 2023-03-25 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dropin',
            options={'verbose_name_plural': 'Drop-Ins'},
        ),
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name_plural': 'Games'},
        ),
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name_plural': 'Sign-ups'},
        ),
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name_plural': 'Stats'},
        ),
    ]
