# Generated by Django 4.1.6 on 2023-03-25 04:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dropins', '0002_alter_dropin_options_alter_games_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='dropInId',
            new_name='dropIn',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='dropInId',
            new_name='dropIn',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='uid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='gid',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='uid',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='dropin',
            name='visible',
            field=models.BooleanField(default=False, help_text='Makes this drop-in visible on the website for users'),
        ),
        migrations.AlterField(
            model_name='rink',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='dropin',
            unique_together={('rink', 'datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='signup',
            unique_together={('user', 'dropIn')},
        ),
        migrations.AlterUniqueTogether(
            name='stats',
            unique_together={('user', 'game')},
        ),
    ]
