# Generated by Django 4.1.6 on 2023-03-25 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropins', '0003_rename_dropinid_games_dropin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='game_number',
            field=models.IntegerField(default=0, help_text='1 = first, 2 = second, etc.'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropins.games'),
        ),
    ]
