# Generated by Django 4.1.6 on 2023-06-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropins', '0004_games_game_number_alter_stats_game'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dropin',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dropin',
            name='goalieFee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dropin',
            name='skaterFee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dropin',
            name='name',
            field=models.CharField(help_text='Name of the drop-in as appears on the Chiller website', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='dropin',
            unique_together={('rink', 'datetime', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='games',
            unique_together={('dropIn', 'game_number')},
        ),
        migrations.AlterUniqueTogether(
            name='rink',
            unique_together={('name', 'address')},
        ),
    ]
