# Generated by Django 4.1.6 on 2023-06-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropins', '0005_alter_dropin_unique_together_dropin_goaliefee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropin',
            name='paypalClientID',
            field=models.CharField(default='Aaqi3vJsOlY29ngwSjglC87C1DmdPkprwnX01YSNptxCQ9COUHCzZy-pKdxa2tFjde6vsJFZ1_-7RC65', help_text='Client ID of the PayPal account that should receive payments for this drop in', max_length=100),
            preserve_default=False,
        ),
    ]
