# Generated by Django 4.1.6 on 2023-07-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skill_level',
            field=models.CharField(choices=[('d', 'D'), ('c', 'C'), ('b', 'B')], default='d', max_length=1),
        ),
    ]
